import { useMemo, useRef, useState } from 'react';
import { BellRing, CalendarDays, Check, CheckCircle2, ChevronRight, Clock3, History, Info, Plus, Send, ShieldCheck, ThumbsDown, ThumbsUp, Trash2, Users, X } from 'lucide-react';
import { Avatar } from './Avatar';
import { Modal } from './Modal';
import { applyPollVote, mutate, rememberBootstrap, request } from '../lib/api';
import { isNativeAndroid, showNativePoll } from '../lib/native';
import { displayName, relativeTime } from '../lib/format';
import { bsDateTime, bsFromDate, bsMonthLength, eventIsoFromSelection, formatBs, relativeDateChoices } from '../lib/nepaliDate';
import type { Bootstrap, Group, Message, Poll } from '../types';

function VoteDetailsModal({poll,onClose}:{poll:Poll;onClose:()=>void}) {
  const labels=new Map(poll.options.map(option=>[option.id,option.label]));
  return <Modal title="Vote details" subtitle={`${poll.voteDetails.length} member${poll.voteDetails.length===1?'':'s'} voted`} onClose={onClose}>
    <div className="vote-detail-list">{poll.voteDetails.map(vote=><article key={vote.userId}><Avatar name={vote.name} color={vote.avatarColor}/><div><strong>{displayName(vote.name)}</strong><small>{relativeTime(vote.createdAt)}</small></div><span className={`choice-${vote.choice}`}>{poll.pollType==='options'?labels.get(vote.choice)||vote.choice:vote.choice==='yes'?'Yes':'No'}</span></article>)}{poll.voteDetails.length===0&&<div className="empty-state"><Users size={30}/><strong>No votes yet</strong></div>}</div>
  </Modal>;
}

function MembersModal({group,onClose}:{group:Group;onClose:()=>void}) {
  return <Modal title="Group Chat" subtitle={`${group.name} members`} onClose={onClose}><div className="member-list">{group.members.map(member=><article key={member.id}><Avatar name={member.name} color={member.avatarColor}/><div><strong>{displayName(member.name)}</strong><small>{member.credentialId}</small></div><span>{member.role}</span></article>)}</div></Modal>;
}

function PollCard({poll,onVote,onOpenAlert,onDelete}:{poll:Poll;onVote:(id:string,choice:string)=>Promise<void>;onOpenAlert:()=>void;onDelete:()=>void}) {
  const [busy,setBusy]=useState(false);const[detailsOpen,setDetailsOpen]=useState(false);
  const total=poll.voteDetails.length;
  const reached=poll.pollType==='options'?total:poll.yesCount;
  const progress=Math.min(100,(reached/poll.minYes)*100);
  const counts=new Map<string,number>();for(const vote of poll.voteDetails)counts.set(vote.choice,(counts.get(vote.choice)||0)+1);
  async function vote(choice:string){setBusy(true);try{await onVote(poll.id,choice)}finally{setBusy(false)}}
  return <article className={`poll-card status-${poll.status}`}>
    <div className="poll-card-top"><div className="live-pill"><i/>{poll.status==='open'?'Voting open':poll.status}</div><strong className="poll-event-inline">{bsDateTime(poll.eventAt)}</strong><div className="poll-card-tools">{poll.status==='open'&&<button className="icon-btn ghost mini" onClick={onOpenAlert} aria-label="Open poll alert"><BellRing size={16}/></button>}{poll.canDelete&&<button className="icon-btn danger mini" onClick={onDelete} aria-label="Delete poll"><Trash2 size={15}/></button>}</div></div>
    <h2>{poll.title}</h2>
    <div className="poll-deadline"><Clock3 size={18}/><span>Voting closes</span><strong>{bsDateTime(poll.deadlineAt)}</strong></div>
    <button className="poll-progress-button" onClick={()=>setDetailsOpen(true)}>
      <div className="poll-progress-head"><span><Users size={16}/><strong>{reached}</strong> of {poll.minYes} required</span><span>{total} voted · tap for details</span></div>
      <div className="poll-progress"><i style={{width:`${progress}%`}}/></div>
    </button>
    {poll.status==='open'?<div className={`vote-actions ${poll.pollType==='options'?'option-votes':''}`}>
      {poll.pollType==='yes_no'?<><button disabled={busy} className={poll.myVote==='yes'?'selected yes':''} onClick={()=>vote('yes')}><ThumbsUp size={18}/> Yes</button><button disabled={busy} className={poll.myVote==='no'?'selected no':''} onClick={()=>vote('no')}><ThumbsDown size={18}/> No</button></>:poll.options.map(option=><button disabled={busy} className={poll.myVote===option.id?'selected yes':''} onClick={()=>vote(option.id)} key={option.id}><span>{option.label}</span><small>{counts.get(option.id)||0}</small></button>)}
    </div>:<div className={`confirmed-box ${poll.status==='cancelled'?'cancelled':''}`}><CheckCircle2 size={22}/><span><strong>{poll.status==='confirmed'?'Confirmed':'Not confirmed'}</strong><small>{poll.pollType==='options'?(poll.winningOptions.map(id=>poll.options.find(option=>option.id===id)?.label||id).join(' / ')||'No winning option'):`${poll.yesCount} Yes · ${poll.noCount} No`}</small></span></div>}
    <footer className="poll-footer"><span>Created by {displayName(poll.creatorName)}</span><span>{poll.pollType==='options'?'Option poll · NOTA included':'Yes / No poll'}</span></footer>
    {detailsOpen&&<VoteDetailsModal poll={poll} onClose={()=>setDetailsOpen(false)}/>}
  </article>;
}

export function PollAlert({group,poll,onClose,onVote}:{group:Group;poll:Poll;onClose:()=>void;onVote:(id:string,choice:string)=>Promise<void>}) {
  const [busy,setBusy]=useState(false);
  async function vote(choice:string){setBusy(true);try{await onVote(poll.id,choice);onClose()}finally{setBusy(false)}}
  return <div className="poll-alert" role="dialog" aria-modal="true"><div className="alert-noise"/><header><div className="brand-mark"><span>स</span></div><span>Sajilo poll</span><button onClick={onClose}><X/></button></header><main><div className="ring-icon"><BellRing size={32}/><i/><i/></div><span className="alert-group">{group.emoji} {group.name}</span><h1>{poll.title}</h1><div className="alert-when"><CalendarDays/><span><strong>{formatBs(bsFromDate(new Date(poll.eventAt)))}</strong><small>{new Date(poll.eventAt).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}</small></span></div></main>{poll.pollType==='yes_no'?<footer><button className="alert-decline" disabled={busy} onClick={()=>vote('no')}><ThumbsDown/><span>No</span></button><button className="alert-dismiss" onClick={onClose}><Clock3/><span>Later</span><small>remind in 2h</small></button><button className="alert-accept" disabled={busy} onClick={()=>vote('yes')}><Check/><span>Yes</span></button></footer>:<div className="alert-option-list">{poll.options.map(option=><button disabled={busy} className={poll.myVote===option.id?'selected':''} onClick={()=>vote(option.id)} key={option.id}>{option.label}</button>)}<button className="later" onClick={onClose}>Later · remind in 2h</button></div>}</div>;
}

function CreatePollModal({group,onClose,onData,notify}:{group:Group;onClose:()=>void;onData:(d:Bootstrap)=>void;notify:(s:string)=>void}) {
  const choices=useMemo(()=>relativeDateChoices(),[]);const initialBs=choices[0].bsDate.split('-').map(Number);
  const [title,setTitle]=useState('');const[dateChoice,setDateChoice]=useState('1');const[time,setTime]=useState('18:00');const[bsYear,setBsYear]=useState(initialBs[0]);const[bsMonth,setBsMonth]=useState(initialBs[1]);const[bsDay,setBsDay]=useState(initialBs[2]);
  const [pollType,setPollType]=useState<'yes_no'|'options'>('yes_no');const[options,setOptions]=useState(['','']);const[minYes,setMinYes]=useState(Math.min(3,group.members.length));const[deadlineHours,setDeadlineHours]=useState(3);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  const maxDay=bsMonthLength(bsYear,bsMonth);const manualBs=`${bsYear}-${String(bsMonth).padStart(2,'0')}-${String(Math.min(bsDay,maxDay)).padStart(2,'0')}`;
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const eventAt=eventIsoFromSelection(dateChoice,time,manualBs);const bsDate=dateChoice==='manual'?manualBs:choices[Number(dateChoice)].bsDate;const d=await mutate(`/groups/${group.id}/polls`,{title,eventAt,bsDate,minYes,deadlineHours,pollType,options});onData(d);notify(group.role==='admin'?'Poll sent to the group':'Poll request sent to an admin');onClose()}catch(err){setError(err instanceof Error?err.message:'Could not create poll.')}finally{setBusy(false)}}
  return <Modal title={group.role==='admin'?'Create a group poll':'Request a group poll'} subtitle={group.role==='admin'?'Members receive it when submitted':'An admin approves it before voting opens'} onClose={onClose} wide><form className="stack-form" onSubmit={submit}>
    <div className="poll-type-toggle"><button type="button" className={pollType==='yes_no'?'active':''} onClick={()=>setPollType('yes_no')}>Yes / No</button><button type="button" className={pollType==='options'?'active':''} onClick={()=>setPollType('options')}>Options</button></div>
    <label><span>{pollType==='options'?'Question':'Poll title'}</span><input placeholder={pollType==='options'?'What should the group choose?':'What are we deciding?'} value={title} onChange={e=>setTitle(e.target.value)}/></label>
    {pollType==='options'&&<div className="option-editor"><span className="field-label">Options</span>{options.map((option,index)=><div key={index}><input placeholder={`Option ${index+1}`} value={option} onChange={e=>setOptions(values=>values.map((value,i)=>i===index?e.target.value:value))}/>{options.length>2&&<button type="button" onClick={()=>setOptions(values=>values.filter((_,i)=>i!==index))}><X size={15}/></button>}</div>)}<button type="button" className="add-option" onClick={()=>setOptions(values=>[...values,''])}><Plus size={15}/> Add option</button><div className="nota-row"><Check size={14}/> NOTA is always included</div></div>}
    <div className="form-two"><label><span>Event date</span><select value={dateChoice} onChange={e=>setDateChoice(e.target.value)}>{choices.map(choice=><option value={choice.value} key={choice.value}>{choice.label} · {formatBs(choice.bsDate)}</option>)}<option value="manual">Manual BS date</option></select></label><label><span>Event time</span><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label></div>
    {dateChoice==='manual'&&<div className="bs-date-selector"><label><span>BS year</span><select value={bsYear} onChange={e=>setBsYear(Number(e.target.value))}>{Array.from({length:8},(_,index)=>initialBs[0]-1+index).map(year=><option key={year}>{year}</option>)}</select></label><label><span>Month</span><select value={bsMonth} onChange={e=>setBsMonth(Number(e.target.value))}>{['Baisakh','Jestha','Ashadh','Shrawan','Bhadra','Ashwin','Kartik','Mangsir','Poush','Magh','Falgun','Chaitra'].map((month,index)=><option value={index+1} key={month}>{month}</option>)}</select></label><label><span>Day</span><select value={Math.min(bsDay,maxDay)} onChange={e=>setBsDay(Number(e.target.value))}>{Array.from({length:maxDay},(_,index)=>index+1).map(day=><option key={day}>{day}</option>)}</select></label></div>}
    <div className="form-two"><label><span>{pollType==='options'?'Minimum votes':'Minimum Yes votes'}</span><input type="number" min="1" max={group.members.length} value={minYes} onChange={e=>setMinYes(Number(e.target.value))}/></label><label><span>Voting closes</span><select value={deadlineHours} onChange={e=>setDeadlineHours(Number(e.target.value))}><option value={24}>1 day before</option><option value={48}>2 days before</option><option value={72}>3 days before</option><option value={168}>1 week before</option><option value={12}>12 hours before</option><option value={6}>6 hours before</option><option value={3}>3 hours before</option></select></label></div>
    <div className="form-hint"><Info size={16}/><span>Results finalize when voting closes. The winning voters receive an event reminder; everyone else receives the result once.</span></div>{error&&<div className="form-error">{error}</div>}<button className="primary-btn full" disabled={busy}><BellRing size={18}/>{busy?'Creating…':group.role==='admin'?'Create poll':'Send for approval'}</button>
  </form></Modal>;
}

export function GroupPage({data,group,userId,onData,notify}:{data:Bootstrap;group:Group;userId:string;onData:(d:Bootstrap)=>void;notify:(s:string)=>void}) {
  const [message,setMessage]=useState('');const[sending,setSending]=useState(false);const[createOpen,setCreateOpen]=useState(false);const[alertPoll,setAlertPoll]=useState<Poll|null>(null);const[membersOpen,setMembersOpen]=useState(false);const[historyOpen,setHistoryOpen]=useState(false);const chatEnd=useRef<HTMLDivElement>(null);
  const activePolls=useMemo(()=>group.polls.filter(p=>p.approvalStatus==='approved'&&p.status==='open'),[group.polls]);const history=group.polls.filter(p=>p.approvalStatus==='approved'&&p.status!=='open');const pendingPolls=group.polls.filter(p=>p.approvalStatus==='pending'&&p.status==='open');
  async function vote(id:string,choice:string){const result=await request<{revision:number}>(`/polls/${id}/vote`,{method:'POST',body:JSON.stringify({choice})});onData(applyPollVote(data,id,choice,result.revision));notify('Vote updated')}
  async function approve(id:string){const d=await mutate(`/polls/${id}/approve`);onData(d);notify('Poll approved')}
  async function remove(id:string){if(!window.confirm('Delete this live poll?'))return;const d=await mutate(`/polls/${id}`,undefined,'DELETE');onData(d);notify('Poll deleted')}
  async function openAlert(poll:Poll){if(isNativeAndroid){await showNativePoll(group,poll);notify('Native poll alert sent');return}setAlertPoll(poll)}
  async function send(e:React.FormEvent){e.preventDefault();if(!message.trim())return;setSending(true);try{const result=await request<{message:Message;revision:number}>(`/groups/${group.id}/messages`,{method:'POST',body:JSON.stringify({body:message})});const next=rememberBootstrap({...data,revision:result.revision,groups:data.groups.map(item=>item.id===group.id?{...item,messages:item.messages.some(existing=>existing.id===result.message.id)?item.messages:[...item.messages,result.message]}:item)});setMessage('');onData(next);setTimeout(()=>chatEnd.current?.scrollIntoView({behavior:'smooth'}),50)}finally{setSending(false)}}
  return <><div className="page-scroll group-page"><section className="group-hero" style={{'--group-accent':group.accent} as React.CSSProperties}><div className="group-title"><span className="group-emoji">{group.emoji}</span><div><span className="eyebrow">Your group</span><h1>{group.name}</h1><p><Users size={14}/>{group.members.length} members · {group.role==='admin'?'You’re an admin':'Member'}</p></div></div><div className="group-actions"><div className="member-stack">{group.members.slice(0,4).map(member=><Avatar key={member.id} name={member.name} color={member.avatarColor} size="sm"/>)}{group.members.length>4&&<span className="member-more">+{group.members.length-4}</span>}</div><button className="poll-create-button" onClick={()=>setCreateOpen(true)}><Plus size={19}/><small>Poll</small></button></div></section>
    <div className="group-layout"><section className="poll-column"><header className="subsection-title"><h2>Active Polls</h2><button className="poll-history-button" onClick={()=>setHistoryOpen(value=>!value)}><History size={15}/> Poll history <span>{history.length}</span></button></header>
      {historyOpen&&<div className="poll-history">{history.map(poll=><article key={poll.id}><span className={`history-status ${poll.status}`}>{poll.status}</span><div><strong>{poll.title}</strong><small>{bsDateTime(poll.eventAt)} · {poll.voteDetails.length} votes</small></div><span>{poll.pollType==='options'?poll.winningOptions.map(id=>poll.options.find(option=>option.id===id)?.label||id).join(' / '):`${poll.yesCount} Yes · ${poll.noCount} No`}</span></article>)}{history.length===0&&<p>No completed polls yet.</p>}</div>}
      <div className="active-poll-list">{activePolls.map(poll=><PollCard key={poll.id} poll={poll} onVote={vote} onOpenAlert={()=>void openAlert(poll)} onDelete={()=>void remove(poll.id)}/>)}{activePolls.length===0&&<div className="empty-state panel"><CalendarDays size={32}/><strong>No active polls</strong><button className="primary-btn small" onClick={()=>setCreateOpen(true)}>Start a poll</button></div>}</div>
      {pendingPolls.length>0&&<div className="approval-list"><span className="field-label">Poll requests · {pendingPolls.length}</span>{pendingPolls.map(poll=><article key={poll.id}><div><strong>{poll.title}</strong><span>{formatBs(poll.bsDate)} · requested by {displayName(poll.creatorName)}</span></div>{group.role==='admin'?<button onClick={()=>approve(poll.id)}><Check size={15}/> Approve</button>:<span className="waiting-pill">Waiting for admin</span>}</article>)}</div>}
      <div className="poll-policy"><ShieldCheck size={19}/><div><strong>Private to this group</strong><p>Poll history is retained for 3 months. Chat is deleted after 10 days.</p></div><ChevronRight size={17}/></div></section>
      <section className="chat-column"><header className="subsection-title chat-title"><button onClick={()=>setMembersOpen(true)}>Group Chat</button></header><div className="chat-list"><div className="date-divider"><span>Last 10 days</span></div>{group.messages.map((msg,index)=>{const mine=msg.userId===userId;const showAvatar=index===0||group.messages[index-1]?.userId!==msg.userId;return <div className={`chat-message ${mine?'mine':''}`} key={msg.id}>{!mine&&showAvatar?<Avatar name={msg.name} color={msg.avatarColor} size="sm"/>:!mine?<span className="avatar-spacer"/>:null}<div>{!mine&&showAvatar&&<span className="chat-name">{displayName(msg.name)}</span>}<p>{msg.body}</p><time>{relativeTime(msg.createdAt)}</time></div></div>})}<div ref={chatEnd}/></div><form className="chat-compose" onSubmit={send}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder={`Message ${group.name}`}/><button className="send-btn" disabled={sending||!message.trim()}><Send size={18}/></button></form></section>
    </div></div>{createOpen&&<CreatePollModal group={group} onClose={()=>setCreateOpen(false)} onData={onData} notify={notify}/>} {alertPoll&&<PollAlert group={group} poll={alertPoll} onClose={()=>setAlertPoll(null)} onVote={vote}/>} {membersOpen&&<MembersModal group={group} onClose={()=>setMembersOpen(false)}/>}</>;
}
