package com.sajilo.split;

import android.content.Context;
import android.graphics.Color;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Spinner;
import android.widget.ArrayAdapter;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.core.widget.NestedScrollView;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import org.json.JSONArray;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

final class HomePageView extends FrameLayout {
    private final MainActivity host;
    private final JSONObject data;

    HomePageView(Context context,MainActivity host){super(context);this.host=host;this.data=host.data();build();}

    private void build(){
        setBackgroundColor(NativeUi.BG);NestedScrollView scroll=new NestedScrollView(getContext());scroll.setFillViewport(true);scroll.setClipToPadding(false);LinearLayout content=new LinearLayout(getContext());content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(15),dp(23),dp(15),dp(30));scroll.addView(content,new NestedScrollView.LayoutParams(-1,-2));addView(scroll,new FrameLayout.LayoutParams(-1,-1));
        TextView title=NativeUi.text(getContext(),"Home",32,NativeUi.INK,true);content.addView(title,new LinearLayout.LayoutParams(-1,dp(49)));
        content.addView(pendingRow(),margin(new LinearLayout.LayoutParams(-1,dp(70)),0,9,0,0));
        LinearLayout balances=new LinearLayout(getContext());balances.setWeightSum(2);balances.addView(balanceCard("↙  Owed to you",data.optJSONObject("totals").optDouble("owedToYou"),NativeUi.POSITIVE),margin(new LinearLayout.LayoutParams(0,dp(72),1),0,0,5,0));balances.addView(balanceCard("↗  You owe",data.optJSONObject("totals").optDouble("youOwe"),NativeUi.NEGATIVE),margin(new LinearLayout.LayoutParams(0,dp(72),1),5,0,0,0));content.addView(balances,margin(new LinearLayout.LayoutParams(-1,dp(72)),0,10,0,0));
        LinearLayout actions=new LinearLayout(getContext());actions.setWeightSum(2);View individual=actionCard("Individual payment",R.drawable.ic_person_add_outline,NativeUi.GREEN_SOFT,NativeUi.GREEN);View group=actionCard("Group request",R.drawable.ic_groups_outline,NativeUi.SAND,NativeUi.INK);actions.addView(individual,margin(new LinearLayout.LayoutParams(0,dp(72),1),0,0,4,0));actions.addView(group,margin(new LinearLayout.LayoutParams(0,dp(72),1),4,0,0,0));content.addView(actions,margin(new LinearLayout.LayoutParams(-1,dp(72)),0,11,0,0));individual.setOnClickListener(v->pickIndividual());group.setOnClickListener(v->showSplit());
        content.addView(ledgerHeader(),margin(new LinearLayout.LayoutParams(-1,dp(65)),0,12,0,0));
        JSONArray items=data.optJSONArray("ledger");RecyclerView list=new RecyclerView(getContext());list.setLayoutManager(new LinearLayoutManager(getContext()));list.setAdapter(new LedgerAdapter(items));list.setNestedScrollingEnabled(true);list.setOverScrollMode(OVER_SCROLL_IF_CONTENT_SCROLLS);list.setBackground(NativeUi.outlined(getContext(),NativeUi.PAPER,NativeUi.LINE,18));list.setClipToOutline(true);NativeUi.elevate(list,3);int count=items==null?0:items.length();int height=Math.min(318,Math.max(90,count*76));content.addView(list,new LinearLayout.LayoutParams(-1,dp(height)));
    }

    private View pendingRow(){LinearLayout row=new LinearLayout(getContext());View incoming=pendingButton("↙","Incoming",data.optJSONObject("payments").optJSONArray("incoming").length(),true);View outgoing=pendingButton("↗","Outgoing",data.optJSONObject("payments").optJSONArray("outgoing").length(),false);row.addView(incoming,margin(new LinearLayout.LayoutParams(0,-1,1),0,0,4,0));row.addView(outgoing,margin(new LinearLayout.LayoutParams(0,-1,1),4,0,0,0));incoming.setOnClickListener(v->showPending(true));outgoing.setOnClickListener(v->showPending(false));return row;}
    private View pendingButton(String arrow,String label,int count,boolean incoming){LinearLayout view=new LinearLayout(getContext());view.setGravity(Gravity.CENTER_VERTICAL);view.setPadding(dp(9),0,dp(8),0);view.setBackground(NativeUi.ripple(getContext(),NativeUi.outlined(getContext(),NativeUi.PAPER,NativeUi.LINE,14)));NativeUi.elevate(view,1);TextView icon=NativeUi.text(getContext(),arrow,17,incoming?NativeUi.GREEN:NativeUi.ORANGE,true);icon.setGravity(Gravity.CENTER);icon.setBackground(NativeUi.shape(getContext(),incoming?NativeUi.GREEN_SOFT:NativeUi.RED_SOFT,11));view.addView(icon,new LinearLayout.LayoutParams(dp(37),dp(37)));LinearLayout words=new LinearLayout(getContext());words.setOrientation(LinearLayout.VERTICAL);words.setGravity(Gravity.CENTER_VERTICAL);words.addView(NativeUi.text(getContext(),label,11,NativeUi.MUTED,false),new LinearLayout.LayoutParams(-1,dp(18)));words.addView(NativeUi.text(getContext(),count+" request"+(count==1?"":"s"),12,NativeUi.INK,true),new LinearLayout.LayoutParams(-1,dp(20)));view.addView(words,margin(new LinearLayout.LayoutParams(0,-2,1),9,0,2,0));TextView next=NativeUi.text(getContext(),"›",20,NativeUi.MUTED,false);next.setGravity(Gravity.CENTER);view.addView(next,new LinearLayout.LayoutParams(dp(18),-1));return view;}
    private View balanceCard(String label,double amount,int background){LinearLayout card=new LinearLayout(getContext());card.setOrientation(LinearLayout.VERTICAL);card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(14),dp(7),dp(13),dp(7));card.setBackground(NativeUi.shape(getContext(),background,16));TextView text=NativeUi.text(getContext(),label,11,Color.argb(210,255,255,255),true);card.addView(text,new LinearLayout.LayoutParams(-1,dp(23)));TextView value=NativeUi.text(getContext(),NativeUi.money(amount),18,Color.WHITE,true);card.addView(value,new LinearLayout.LayoutParams(-1,dp(29)));return card;}
    private View actionCard(String label,int drawable,int background,int tint){LinearLayout card=new LinearLayout(getContext());card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(10),0,dp(9),0);card.setBackground(NativeUi.ripple(getContext(),NativeUi.shape(getContext(),background,16)));ImageView icon=NativeUi.icon(getContext(),drawable,tint,9);icon.setBackground(NativeUi.shape(getContext(),Color.argb(185,255,255,255),12));card.addView(icon,new LinearLayout.LayoutParams(dp(40),dp(40)));TextView text=NativeUi.text(getContext(),label,12,NativeUi.INK,true);text.setMaxLines(2);card.addView(text,margin(new LinearLayout.LayoutParams(0,-1,1),9,0,3,0));ImageView send=NativeUi.icon(getContext(),R.drawable.ic_send_outline,Color.WHITE,8);send.setBackground(NativeUi.shape(getContext(),NativeUi.INK,18));card.addView(send,new LinearLayout.LayoutParams(dp(34),dp(34)));return card;}
    private View ledgerHeader(){LinearLayout row=new LinearLayout(getContext());row.setGravity(Gravity.BOTTOM);LinearLayout words=new LinearLayout(getContext());words.setOrientation(LinearLayout.VERTICAL);TextView eyebrow=NativeUi.text(getContext(),"YOUR BALANCES",9,NativeUi.MUTED,true);eyebrow.setLetterSpacing(.13f);words.addView(eyebrow,new LinearLayout.LayoutParams(-1,dp(20)));words.addView(NativeUi.text(getContext(),"Ledger",25,NativeUi.INK,true),new LinearLayout.LayoutParams(-1,dp(38)));row.addView(words,new LinearLayout.LayoutParams(0,-1,1));LinearLayout totals=new LinearLayout(getContext());totals.setGravity(Gravity.BOTTOM);TextView green=NativeUi.text(getContext(),NativeUi.money(data.optJSONObject("totals").optDouble("owedToYou")),11,NativeUi.GREEN,true);TextView red=NativeUi.text(getContext(),NativeUi.money(data.optJSONObject("totals").optDouble("youOwe")),11,NativeUi.RED,true);totals.addView(green);totals.addView(red,margin(new LinearLayout.LayoutParams(-2,dp(30)),10,0,0,0));row.addView(totals,new LinearLayout.LayoutParams(-2,dp(40)));return row;}

    private final class LedgerAdapter extends RecyclerView.Adapter<LedgerAdapter.Holder>{final List<JSONObject> values;LedgerAdapter(JSONArray items){values=NativeUi.objects(items);}final class Holder extends RecyclerView.ViewHolder{final LinearLayout row;Holder(LinearLayout view){super(view);row=view;}}@NonNull public Holder onCreateViewHolder(@NonNull ViewGroup p,int t){LinearLayout row=new LinearLayout(getContext());row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(11),dp(8),dp(10),dp(8));row.setBackground(NativeUi.outlined(getContext(),NativeUi.PAPER,NativeUi.LINE,0));row.setLayoutParams(new RecyclerView.LayoutParams(-1,dp(76)));return new Holder(row);}@Override public void onBindViewHolder(@NonNull Holder holder,int position){JSONObject item=values.get(position);holder.row.removeAllViews();JSONObject person=person(item.optString("personId"));String name=item.optString("name");TextView avatar=NativeUi.avatar(getContext(),name,item.optString("avatarColor"),43);holder.row.addView(avatar);LinearLayout words=new LinearLayout(getContext());words.setOrientation(LinearLayout.VERTICAL);words.setGravity(Gravity.CENTER_VERTICAL);words.addView(NativeUi.text(getContext(),NativeUi.displayName(name),13,NativeUi.INK,true),new LinearLayout.LayoutParams(-1,dp(22)));double amount=item.optDouble("amount");words.addView(NativeUi.text(getContext(),amount>0?"owes you":"you owe them",10,NativeUi.MUTED,false),new LinearLayout.LayoutParams(-1,dp(18)));holder.row.addView(words,margin(new LinearLayout.LayoutParams(0,-1,1),10,0,5,0));TextView value=NativeUi.text(getContext(),(amount>0?"+ ":"− ")+NativeUi.money(Math.abs(amount)),12,amount>0?NativeUi.GREEN:NativeUi.RED,true);holder.row.addView(value);TextView pay=NativeUi.button(getContext(),"Pay",Color.WHITE,NativeUi.GREEN,10);pay.setContentDescription("Pay "+name);holder.row.addView(pay,margin(new LinearLayout.LayoutParams(dp(48),dp(37)),7,0,0,0));TextView add=NativeUi.button(getContext(),"＋",NativeUi.INK,Color.rgb(248,248,244),10);add.setTextSize(19);add.setBackground(NativeUi.ripple(getContext(),NativeUi.outlined(getContext(),Color.rgb(248,248,244),NativeUi.LINE,10)));holder.row.addView(add,margin(new LinearLayout.LayoutParams(dp(37),dp(37)),5,0,0,0));holder.row.setOnClickListener(v->showHistory(person));pay.setOnClickListener(v->host.payPerson(person));add.setOnClickListener(v->showLend(person));}@Override public int getItemCount(){return values.size();}}

    private JSONObject person(String id){for(JSONObject person:NativeUi.objects(data.optJSONArray("people")))if(id.equals(person.optString("id")))return person;JSONObject empty=new JSONObject();try{empty.put("id",id);empty.put("name","Member");empty.put("avatarColor","#687FBC");}catch(Exception ignored){}return empty;}
    private void showHistory(JSONObject person){LinearLayout content=dialogContent();String userId=data.optJSONObject("user").optString("id"),personId=person.optString("id");int count=0;for(JSONObject item:NativeUi.objects(data.optJSONArray("transactions"))){boolean match=(userId.equals(item.optString("payerId"))&&personId.equals(item.optString("payeeId")))||(userId.equals(item.optString("payeeId"))&&personId.equals(item.optString("payerId")));if(!match)continue;count++;boolean incoming=userId.equals(item.optString("payeeId"));content.addView(historyRow(item,incoming),margin(new LinearLayout.LayoutParams(-1,-2),0,0,0,8));}if(count==0)content.addView(emptyCard("No verified transactions","Completed payments between you will appear here."),new LinearLayout.LayoutParams(-1,dp(120)));FundshipSheet.show(getContext(),"Ledger","History with "+NativeUi.displayName(person.optString("name")),count+" verified transaction"+(count==1?"":"s"),content,null,86,null);}
    private View historyRow(JSONObject item,boolean incoming){LinearLayout row=new LinearLayout(getContext());row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(10),dp(9),dp(10),dp(9));row.setBackground(NativeUi.outlined(getContext(),Color.WHITE,NativeUi.LINE,12));LinearLayout words=new LinearLayout(getContext());words.setOrientation(LinearLayout.VERTICAL);words.addView(NativeUi.text(getContext(),item.optString("purpose"),14,NativeUi.INK,true));words.addView(NativeUi.text(getContext(),NativeUi.relative(item.optString("createdAt"))+" · "+item.optString("kind"),11,NativeUi.MUTED,false));row.addView(words,new LinearLayout.LayoutParams(0,-2,1));row.addView(NativeUi.text(getContext(),(incoming?"+ ":"− ")+NativeUi.money(item.optDouble("amount")),14,incoming?NativeUi.GREEN:NativeUi.RED,true));return row;}

    private void pickIndividual(){List<JSONObject> people=NativeUi.objects(data.optJSONArray("people"));LinearLayout content=dialogContent();FundshipSheet[] sheetRef=new FundshipSheet[1];for(JSONObject person:people){LinearLayout item=personRow(person,"Send an individual payment request");TextView next=NativeUi.text(getContext(),"›",22,NativeUi.MUTED,false);next.setGravity(Gravity.CENTER);item.addView(next,new LinearLayout.LayoutParams(dp(28),dp(42)));content.addView(item,margin(new LinearLayout.LayoutParams(-1,-2),0,0,0,8));item.setOnClickListener(v->{sheetRef[0].dismiss();showLend(person);});}if(people.isEmpty())content.addView(emptyCard("No connections yet","Connect with someone before sending a request."),new LinearLayout.LayoutParams(-1,dp(120)));sheetRef[0]=FundshipSheet.show(getContext(),"Payments","Choose a person","Select who should confirm the money you lent.",content,null,84,null);}
    private void showLend(JSONObject person){LinearLayout form=new LinearLayout(getContext());form.setOrientation(LinearLayout.VERTICAL);form.addView(personRow(person,"They will receive this in Incoming requests"),new LinearLayout.LayoutParams(-1,-2));EditText amount=input("Amount in NPR",true),purpose=input("What was it for?",false),note=input("Optional note",false);form.addView(NativeUi.labeled(getContext(),"Amount",amount,"Enter the amount you gave in real life."),margin(new LinearLayout.LayoutParams(-1,-2),0,16,0,0));form.addView(NativeUi.labeled(getContext(),"Purpose",purpose,"A short description helps both people identify it."),margin(new LinearLayout.LayoutParams(-1,-2),0,12,0,0));form.addView(NativeUi.labeled(getContext(),"Note",note,"Optional additional context."),margin(new LinearLayout.LayoutParams(-1,-2),0,12,0,0));FundshipSheet.show(getContext(),"Individual request","Request from "+NativeUi.displayName(person.optString("name")),"Record money you already lent; the other person must verify it.",form,"Send request",88,sheet->{String cleanPurpose=purpose.getText().toString().trim();double value;try{value=Double.parseDouble(amount.getText().toString());}catch(Exception error){amount.setError("Enter a valid amount");amount.requestFocus();return;}if(value<=0){amount.setError("Amount must be greater than zero");return;}if(cleanPurpose.isEmpty()){purpose.setError("Enter a purpose");purpose.requestFocus();return;}JSONObject body=new JSONObject();try{body.put("borrowerId",person.optString("id"));body.put("amount",value);body.put("purpose",cleanPurpose);body.put("note",note.getText().toString().trim());}catch(Exception ignored){}sheet.dismiss();host.api().post("/payments/lend",body,host.callbackRefresh("Payment request sent"));});}

    private void showPending(boolean incoming){JSONArray items=data.optJSONObject("payments").optJSONArray(incoming?"incoming":"outgoing");LinearLayout content=dialogContent();FundshipSheet[] sheetRef=new FundshipSheet[1];for(JSONObject item:NativeUi.objects(items)){LinearLayout row=pendingRequestRow(item,incoming);if(incoming){TextView verify=NativeUi.button(getContext(),"Verify",Color.WHITE,NativeUi.GREEN,9);row.addView(verify,margin(new LinearLayout.LayoutParams(dp(72),dp(38)),8,0,0,0));verify.setOnClickListener(v->{sheetRef[0].dismiss();verifyPayment(item);});}content.addView(row,margin(new LinearLayout.LayoutParams(-1,-2),0,0,0,8));}if(items.length()==0)content.addView(emptyCard("No pending requests",incoming?"New requests for you will appear here.":"Requests you send will appear here."),new LinearLayout.LayoutParams(-1,dp(120)));String primary=incoming&&items.length()>1?"Confirm all requests":null;sheetRef[0]=FundshipSheet.show(getContext(),"Payments",incoming?"Incoming requests":"Outgoing requests",items.length()+" pending request"+(items.length()==1?"":"s"),content,primary,88,sheet->{sheet.dismiss();verifyAll();});}
    private void verifyPayment(JSONObject item){host.authenticate("Confirm payment",item.optString("purpose"),"Use MPIN",()->host.api().post("/payments/"+item.optString("id")+"/verify",new JSONObject(),host.callbackRefresh("Payment verified")),()->showMpin(()->host.api().post("/payments/"+item.optString("id")+"/verify",new JSONObject(),host.callbackRefresh("Payment verified"))));}
    private void verifyAll(){host.authenticate("Confirm all payments","Verify every incoming request","Use MPIN",()->host.api().post("/payments/verify-all",new JSONObject(),host.callbackRefresh("All payments verified")),()->showMpin(()->host.api().post("/payments/verify-all",new JSONObject(),host.callbackRefresh("All payments verified"))));}
    private void showMpin(Runnable verified){LinearLayout form=new LinearLayout(getContext());form.setOrientation(LinearLayout.VERTICAL);EditText mpin=input("4-digit MPIN",true);mpin.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);form.addView(NativeUi.labeled(getContext(),"MPIN",mpin,"Use your four-digit FUNDSHIP MPIN."),new LinearLayout.LayoutParams(-1,-2));FundshipSheet.show(getContext(),"Security check","Use MPIN","Fingerprint was cancelled or unavailable.",form,"Verify",66,sheet->{String value=mpin.getText().toString();if(!value.matches("^\\d{4}$")){mpin.setError("Enter your 4-digit MPIN");return;}sheet.setBusy(true,"Verifying…","Verify");JSONObject body=new JSONObject();try{body.put("mpin",value);}catch(Exception ignored){}host.api().post("/auth/verify-mpin",body,new FundsApi.Callback(){public void success(JSONObject ignored){sheet.dismiss();verified.run();}public void error(String message){sheet.setBusy(false,"","Verify");host.toast(message);}});});}

    private void showSplit(){
        LinearLayout form=new LinearLayout(getContext());form.setOrientation(LinearLayout.VERTICAL);EditText purpose=input("What is this payment for?",false),total=input("Total amount in NPR",true);form.addView(NativeUi.labeled(getContext(),"Purpose",purpose,"Everyone will see this description."),new LinearLayout.LayoutParams(-1,-2));form.addView(NativeUi.labeled(getContext(),"Total amount",total,"The complete amount shared by all selected people."),margin(new LinearLayout.LayoutParams(-1,-2),0,12,0,0));Spinner mode=NativeUi.spinner(getContext(),new String[]{"Equal split","Manual split"});form.addView(NativeUi.labeled(getContext(),"Split mode",mode,"Equal includes you; manual lets you set every share."),margin(new LinearLayout.LayoutParams(-1,-2),0,12,0,0));
        TextView peopleTitle=NativeUi.fieldLabel(getContext(),"Participants");form.addView(peopleTitle,margin(new LinearLayout.LayoutParams(-1,dp(28)),0,14,0,0));LinearLayout peopleBox=new LinearLayout(getContext());peopleBox.setOrientation(LinearLayout.VERTICAL);form.addView(peopleBox);List<JSONObject> people=new ArrayList<>();people.add(data.optJSONObject("user"));people.addAll(NativeUi.objects(data.optJSONArray("people")));Map<String,CheckBox> checks=new LinkedHashMap<>();Map<String,EditText> amounts=new LinkedHashMap<>();Map<String,EditText> notes=new LinkedHashMap<>();Map<String,LinearLayout> manualRows=new LinkedHashMap<>();for(JSONObject person:people){String id=person.optString("id");LinearLayout card=NativeUi.sectionCard(getContext());card.setPadding(dp(10),dp(8),dp(10),dp(8));LinearLayout identity=new LinearLayout(getContext());identity.setGravity(Gravity.CENTER_VERTICAL);TextView avatar=NativeUi.avatar(getContext(),person.optString("name"),person.optString("avatarColor"),36);identity.addView(avatar,new LinearLayout.LayoutParams(dp(36),dp(36)));CheckBox check=new CheckBox(getContext());boolean self=id.equals(data.optJSONObject("user").optString("id"));check.setText(self?"You":NativeUi.displayName(person.optString("name")));check.setTextColor(NativeUi.INK);check.setChecked(self);check.setEnabled(!self);identity.addView(check,margin(new LinearLayout.LayoutParams(0,dp(44),1),8,0,0,0));card.addView(identity,new LinearLayout.LayoutParams(-1,dp(44)));LinearLayout manualRow=new LinearLayout(getContext());EditText share=input("Share",true),note=input("Optional note",false);manualRow.addView(share,new LinearLayout.LayoutParams(0,dp(46),1));manualRow.addView(note,margin(new LinearLayout.LayoutParams(0,dp(46),1),7,0,0,0));manualRow.setVisibility(GONE);card.addView(manualRow,margin(new LinearLayout.LayoutParams(-1,dp(46)),0,6,0,0));peopleBox.addView(card,margin(new LinearLayout.LayoutParams(-1,-2),0,0,0,8));checks.put(id,check);amounts.put(id,share);notes.put(id,note);manualRows.put(id,manualRow);}
        Runnable update=()->{boolean manual=mode.getSelectedItemPosition()==1;for(String id:checks.keySet())manualRows.get(id).setVisibility(manual&&checks.get(id).isChecked()?VISIBLE:GONE);};mode.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){update.run();}public void onNothingSelected(android.widget.AdapterView<?> p){}});for(CheckBox check:checks.values())check.setOnCheckedChangeListener((button,checked)->update.run());
        FundshipSheet.show(getContext(),"Payments","Group payment request","Choose participants and how the total should be divided.",form,"Initiate request",94,sheet->{String cleanPurpose=purpose.getText().toString().trim();double totalValue;try{totalValue=Double.parseDouble(total.getText().toString());}catch(Exception error){total.setError("Enter a valid total");return;}if(cleanPurpose.isEmpty()){purpose.setError("Enter a purpose");return;}if(totalValue<=0){total.setError("Total must be greater than zero");return;}int selectedCount=0;for(CheckBox check:checks.values())if(check.isChecked())selectedCount++;if(selectedCount<2){host.toast("Select at least one other person.");return;}JSONObject body=new JSONObject();JSONArray participants=new JSONArray();double manualTotal=0;try{for(JSONObject person:people){String id=person.optString("id");if(!checks.get(id).isChecked())continue;JSONObject entry=new JSONObject();entry.put("userId",id);if(mode.getSelectedItemPosition()==1){double share=Double.parseDouble(amounts.get(id).getText().toString());if(share<=0){amounts.get(id).setError("Required");return;}manualTotal+=share;entry.put("amount",share);entry.put("note",notes.get(id).getText().toString().trim());}participants.put(entry);}if(mode.getSelectedItemPosition()==1&&Math.abs(manualTotal-totalValue)>.01){total.setError("Manual shares must total "+NativeUi.money(totalValue));return;}body.put("purpose",cleanPurpose);body.put("totalAmount",totalValue);body.put("participants",participants);body.put("mode",mode.getSelectedItemPosition()==1?"manual":"equal");}catch(Exception error){host.toast("Complete every selected share.");return;}sheet.dismiss();host.api().post("/payments/split",body,host.callbackRefresh("Group request sent"));});
    }

    private LinearLayout personRow(JSONObject person,String subtitle){LinearLayout row=new LinearLayout(getContext());row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(11),dp(10),dp(11),dp(10));row.setBackground(NativeUi.outlined(getContext(),Color.WHITE,NativeUi.LINE,13));TextView avatar=NativeUi.avatar(getContext(),person.optString("name"),person.optString("avatarColor"),42);row.addView(avatar,new LinearLayout.LayoutParams(dp(42),dp(42)));LinearLayout words=new LinearLayout(getContext());words.setOrientation(LinearLayout.VERTICAL);words.addView(NativeUi.text(getContext(),NativeUi.displayName(person.optString("name")),14,NativeUi.INK,true),new LinearLayout.LayoutParams(-1,dp(23)));words.addView(NativeUi.text(getContext(),subtitle,10,NativeUi.MUTED,false),new LinearLayout.LayoutParams(-1,dp(18)));row.addView(words,margin(new LinearLayout.LayoutParams(0,-2,1),10,0,5,0));return row;}
    private LinearLayout pendingRequestRow(JSONObject item,boolean incoming){LinearLayout row=new LinearLayout(getContext());row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(11),dp(10),dp(11),dp(10));row.setBackground(NativeUi.outlined(getContext(),Color.WHITE,NativeUi.LINE,13));TextView badge=NativeUi.text(getContext(),incoming?"↙":"↗",17,incoming?NativeUi.GREEN:NativeUi.ORANGE,true);badge.setGravity(Gravity.CENTER);badge.setBackground(NativeUi.shape(getContext(),incoming?NativeUi.GREEN_SOFT:NativeUi.RED_SOFT,11));row.addView(badge,new LinearLayout.LayoutParams(dp(40),dp(40)));LinearLayout words=new LinearLayout(getContext());words.setOrientation(LinearLayout.VERTICAL);words.addView(NativeUi.text(getContext(),item.optString("purpose"),14,NativeUi.INK,true),new LinearLayout.LayoutParams(-1,dp(23)));String person=incoming?item.optString("payeeName"):item.optString("payerName");words.addView(NativeUi.text(getContext(),(incoming?"From ":"To ")+NativeUi.displayName(person)+" · "+NativeUi.relative(item.optString("createdAt")),10,NativeUi.MUTED,false),new LinearLayout.LayoutParams(-1,dp(18)));row.addView(words,margin(new LinearLayout.LayoutParams(0,-2,1),10,0,6,0));row.addView(NativeUi.text(getContext(),NativeUi.money(item.optDouble("amount")),13,incoming?NativeUi.RED:NativeUi.GREEN,true));return row;}
    private View emptyCard(String title,String subtitle){LinearLayout empty=NativeUi.sectionCard(getContext());empty.setGravity(Gravity.CENTER);TextView heading=NativeUi.text(getContext(),title,15,NativeUi.INK,true);heading.setGravity(Gravity.CENTER);empty.addView(heading,new LinearLayout.LayoutParams(-1,dp(37)));TextView copy=NativeUi.text(getContext(),subtitle,11,NativeUi.MUTED,false);copy.setGravity(Gravity.CENTER);copy.setTextAlignment(View.TEXT_ALIGNMENT_CENTER);empty.addView(copy,new LinearLayout.LayoutParams(-1,dp(45)));return empty;}

    private LinearLayout dialogContent(){LinearLayout value=new LinearLayout(getContext());value.setOrientation(LinearLayout.VERTICAL);value.setPadding(dp(10),dp(8),dp(10),dp(8));return value;}
    private ScrollView scroll(View child,int height){ScrollView scroll=new ScrollView(getContext());scroll.addView(child);scroll.setLayoutParams(new ViewGroup.LayoutParams(-1,dp(height)));return scroll;}
    private EditText input(String hint,boolean number){EditText input=new EditText(getContext());input.setHint(hint);input.setTextSize(14);input.setTextColor(NativeUi.INK);input.setSingleLine(true);input.setPadding(dp(12),0,dp(12),0);input.setBackground(NativeUi.outlined(getContext(),Color.WHITE,NativeUi.LINE,11));if(number)input.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);return input;}
    private LinearLayout.LayoutParams rowParams(){return new LinearLayout.LayoutParams(-1,dp(50));}
    private int dp(int value){return NativeUi.dp(getContext(),value);}private <T extends ViewGroup.MarginLayoutParams>T margin(T p,int l,int t,int r,int b){return NativeUi.margins(getContext(),p,l,t,r,b);}
}
